[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "aetherflow-scheduler"
version = "0.0.14"
description = "APScheduler integration for aetherflow-core."
readme = "README.md"
requires-python = ">=3.10"
license-files = ["LICEN[CS]E*"]
authors = [{name="aetherflow contributors"}]
dependencies = ["aetherflow-core>=0.0.1", "APScheduler>=3.10", "PyYAML>=6.0"]

[project.scripts]
aetherflow-scheduler = "aetherflow.scheduler.cli:main"

[project.urls]
Homepage = "https://github.com/aicodedao/aetherflow"
Source = "https://github.com/aicodedao/aetherflow/tree/master/packages/aetherflow-scheduler"
Documentation = "https://github.com/aicodedao/aetherflow/tree/master/docs"
license = "https://github.com/aicodedao/aetherflow/blob/master/LICENSE"
"Bug Tracker" = "https://github.com/aicodedao/aetherflow/issues"
CI = "https://github.com/aicodedao/aetherflow/blob/master/.github/workflows/ci.yaml"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
namespaces = true
include = ["aetherflow.scheduler*"]
