[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "aetherflow"
version = "0.0.15rc1"
description = "AetherFlow meta package (convenience wrapper for core + scheduler)"
readme = "README.md"
requires-python = ">=3.10"
license-files = ["LICEN[CS]E*"]
dependencies = [
  "aetherflow-core>=0.0.1",
  "aetherflow-scheduler>=0.0.0"
]

[project.urls]
Homepage = "https://github.com/aicodedao/aetherflow"
Source = "https://github.com/aicodedao/aetherflow/tree/master/packages/aetherflow"
Documentation = "https://github.com/aicodedao/aetherflow/tree/master/docs"
license = "https://github.com/aicodedao/aetherflow/blob/master/LICENSE"
"Bug Tracker" = "https://github.com/aicodedao/aetherflow/issues"
CI = "https://github.com/aicodedao/aetherflow/blob/master/.github/workflows/ci.yaml"

[tool.setuptools]
packages = []